### ISSUE TITLE
Add empty folders to the download

### ISSUE THREAD

**Issue by mskrss** [LlamaPag/bastion#2]
In the download, in the save file, there's only a datapacks folder, which confuses a lot of people since all other practice maps have way more folders, therefore they think they must've missed something/extracted in the wrong way/... . I would suggest just adding empty folders that would generate later regardless.

**Comment by LlamaPag** [comment]
Modified the installation instructions in the [readme](https://github.com/LlamaPag/bastion/blob/main/README.md) to include the correct folder structure.
